// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMcsSz_qmlsqjLQ3o4qwbrblVqxSM_9m4',
    appId: '1:329373414923:web:daef95da0a88af8c99f90e',
    messagingSenderId: '329373414923',
    projectId: 'fortnite-ranked-tracker-7ee82',
    authDomain: 'fortnite-ranked-tracker-7ee82.firebaseapp.com',
    storageBucket: 'fortnite-ranked-tracker-7ee82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gkYt7LkqAqaAinLMmMpkfZDP3bo3WRc',
    appId: '1:329373414923:android:783c0e391f78ce9b99f90e',
    messagingSenderId: '329373414923',
    projectId: 'fortnite-ranked-tracker-7ee82',
    storageBucket: 'fortnite-ranked-tracker-7ee82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC83MBgKOQBdQI5csYey163P35LnKt1aTI',
    appId: '1:329373414923:ios:e8e2e47f44bfe0ec99f90e',
    messagingSenderId: '329373414923',
    projectId: 'fortnite-ranked-tracker-7ee82',
    storageBucket: 'fortnite-ranked-tracker-7ee82.appspot.com',
    iosBundleId: 'com.pyflat.fortniterankedtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC83MBgKOQBdQI5csYey163P35LnKt1aTI',
    appId: '1:329373414923:ios:e8e2e47f44bfe0ec99f90e',
    messagingSenderId: '329373414923',
    projectId: 'fortnite-ranked-tracker-7ee82',
    storageBucket: 'fortnite-ranked-tracker-7ee82.appspot.com',
    iosBundleId: 'com.pyflat.fortniterankedtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMcsSz_qmlsqjLQ3o4qwbrblVqxSM_9m4',
    appId: '1:329373414923:web:bcdd15e6d9739cf199f90e',
    messagingSenderId: '329373414923',
    projectId: 'fortnite-ranked-tracker-7ee82',
    authDomain: 'fortnite-ranked-tracker-7ee82.firebaseapp.com',
    storageBucket: 'fortnite-ranked-tracker-7ee82.appspot.com',
  );
}
